services:
  # Base de datos relacional (Historial, usuarios)
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ai_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Base de datos vectorial (RAG Clínico)
  qdrant:
    image: qdrant/qdrant:v1.10.1
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  pgdata:
  qdrant_data:
